Requires Changes (#6)
* Update README.md

* Add new endpoints

* Fix error ts2367

* feat: Handling Secrets with Environment Variables

* fix: Migrate to use Node.js v14

* feat: Add endpoint to filter an image from a public url

* Update README.md

Add an endpoint URL for a running elastic beanstalk deployment

* Add authentication feature (#4)

* Use Bcrypt to Generated Salted Hashed Passwords

* Use Bcrypt to Compare password to Salted Hashed Password

* Activate function requireAuth

---------

Co-authored-by: Hossam Alzamly <hossam.alzamly@operaize.com>

* fix: Set variables and parameter types

* fix: Add status codes to your responses

---------

Co-authored-by: Hossam Alzamly <hossam.alzamly@operaize.com>